modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="forgestory" #mandatory
version="1.0-beta" #mandatory
displayName="ForgeStory" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="forgestory.png" #optional
#credits="" #optional
authors="VuzZ" #optional
description='''
'''
[[dependencies.forgestory]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.forgestory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
